export interface OperationRecordType{
    UnkCode: number;
    OperationId: number;
    Centercode:number;
    MrNO: string;
    IPDCode: string;
    Otdate: string;
    Starttime: string;
    EndTime: string;
    PreOPDiagnosis: string;
    PostOpDiagnosis: string;
    Diagnosis: string;
    Surgery: string;
    SurgeryGroup: string;
    OTProcedure: string;
    Closure: string;
    CultureSensitivity: string;
    BIOPSY: string;
    IMPLANT: string;
    DEPARTMENT: string;
    REMARKS: string;
    C_DATE: string;
    DE_ACTIVE:string;
    m_DATE: string;
    c_user: number;
    m_user:  number;
    SubDepartment: number;
    ServiceCodeId: number;
    Op_Preposed: string;
    Op_Executed: string;
    anesthesiaGroup: string;
    SkinIncisionTime: string;
    SkinClosureTime: string;
    BloodLoss: string;
    Counts: string;
    IIUsage: string;
    Histopathology: string;
    RegType: number;
}